# Generated by Django 2.2.12 on 2020-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200410_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('out of delivery', 'out of delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
